Repository hubatrifusz/elevate, pull requests merged in 2025-03, with the labels that each got.

#68 19 add friendrequest model and update other components accordingly
  Backend/Elevate.Models/Friendship/Friendship.cs
  Backend/Elevate.Models/Friendship/FriendshipDto.cs
  Backend/Elevate.Models/Friendship/FriendshipStatusEnum.cs
  Backend/Elevate.Models/Friendship/FriendshipUpdateDto.cs
  Backend/Elevate.Models/Habit/FrequencyEnum.cs
  Backend/Elevate/Controllers/FriendshipController.cs
Labels: enhancement

#71 Added automatic habit log generation.
  Backend/Elevate.Data/Repository/HabitLogGeneratorRepository.cs
  Backend/Elevate.Data/Repository/HabitRepository.cs
  Backend/Elevate.Models/Friendship/Friendship.cs
  Backend/Elevate/Controllers/HabitController.cs
  Backend/Elevate/Extensions/IServiceCollectionExtension.cs
  Backend/Elevate/Services/HabitLogGenerationBackgroundService.cs
  Backend/Elevate/Services/HabitLogGeneratorService.cs
  Backend/Elevate/Services/IHabitLogGeneratorService.cs
Labels: bug, enhancement

#76 75 create frequency enum converter
  Backend/Elevate.Common/Elevate.Common.csproj
  Backend/Elevate.Models/Habit/HabitCreateDto.cs
  Backend/Elevate.Models/Habit/HabitDto.cs
  Backend/Elevate.Models/Habit/HabitModel.cs
  Backend/Elevate.Models/Habit/HabitUpdateDto.cs
  Backend/Elevate/Profiles/AutoMapperProfile.cs
Labels: bug, enhancement

#80 fixed crashing
  Backend/Elevate/Controllers/HabitController.cs
Labels: bug

#86 84 fix no route matches the given value error on habit post
  Backend/Elevate.Common/Utilities/UserPermissionUtility.cs
  Backend/Elevate.Data/Migrations/20250306171058_UpdatedHabitFieldTypes.cs
  Backend/Elevate.Data/Migrations/20250310170828_UpdatedFrequencyType.Designer.cs
  Backend/Elevate.Data/Migrations/20250310170828_UpdatedFrequencyType.cs
  Backend/Elevate.Data/Repository/HabitRepository.cs
  Backend/Elevate/Controllers/HabitController.cs
  Backend/Elevate/Profiles/AutoMapperProfile.cs
  Backend/Elevate/Profiles/IntToFrequencyEnumConverter.cs
  Backend/Elevate/Services/HabitLogGeneratorService.cs
  Backend/Elevate/Services/HabitService.cs
  Backend/Elevate/Services/IHabitService.cs
Labels: bug

#90 Added GET habitlog/duedate endpoint
  Backend/Elevate.Data/Repository/HabitLogRepository.cs
  Backend/Elevate/Controllers/HabitLogController.cs
  Backend/Elevate/Services/HabitLogService.cs
  Backend/Elevate/Services/IHabitLogService.cs
Labels: enhancement

#92 91 refactor backend code and structure
  Backend/Elevate.Common/Exceptions/Exceptions.cs
  Backend/Elevate.Common/Utilities/UserPermissionUtility.cs
  Backend/Elevate.Data/Repository/FriendshipRepository.cs
  Backend/Elevate.Data/Repository/HabitLogRepository.cs
  Backend/Elevate.Data/Repository/HabitRepository.cs
  Backend/Elevate.Data/Repository/UserRepository.cs
  Backend/Elevate.Models/User/IdentityResultWithUser.cs
  Backend/Elevate.Models/User/UserIdWithJWT.cs
  Backend/Elevate/Controllers/AuthController.cs
  Backend/Elevate/Controllers/FriendshipController.cs
  Backend/Elevate/Controllers/HabitController.cs
  Backend/Elevate/Controllers/HabitLogController.cs
  Backend/Elevate/Controllers/UserController.cs
  Backend/Elevate/Elevate.csproj
  Backend/Elevate/Extensions/IServiceCollectionExtension.cs
  Backend/Elevate/Middleware/GlobalExceptionHandler.cs
  Backend/Elevate/Profiles/AutoMapperProfile.cs
  Backend/Elevate/Program.cs
  Backend/Elevate/Services/FriendshipService.cs
  Backend/Elevate/Services/HabitLogService.cs
  Backend/Elevate/Services/HabitService.cs
  Backend/Elevate/Services/IFriendshipService.cs
  Backend/Elevate/Services/IHabitLogService.cs
  Backend/Elevate/Services/IHabitService.cs
  Backend/Elevate/Services/IUserService.cs
  Backend/Elevate/Services/UserService.cs
Labels: enhancement

#93 Backend
  Backend/Elevate.Common/Exceptions/Exceptions.cs
  Backend/Elevate.Common/Utilities/UserPermissionUtility.cs
  Backend/Elevate.Data/Repository/FriendshipRepository.cs
  Backend/Elevate.Data/Repository/HabitLogRepository.cs
  Backend/Elevate.Data/Repository/HabitRepository.cs
  Backend/Elevate.Data/Repository/UserRepository.cs
  Backend/Elevate.Models/User/IdentityResultWithUser.cs
  Backend/Elevate.Models/User/UserIdWithJWT.cs
  Backend/Elevate/Controllers/AuthController.cs
  Backend/Elevate/Controllers/FriendshipController.cs
  Backend/Elevate/Controllers/HabitController.cs
  Backend/Elevate/Controllers/HabitLogController.cs
  Backend/Elevate/Controllers/UserController.cs
  Backend/Elevate/Elevate.csproj
  Backend/Elevate/Extensions/IServiceCollectionExtension.cs
  Backend/Elevate/Middleware/GlobalExceptionHandler.cs
  Backend/Elevate/Profiles/AutoMapperProfile.cs
  Backend/Elevate/Program.cs
  Backend/Elevate/Services/FriendshipService.cs
  Backend/Elevate/Services/HabitLogService.cs
  Backend/Elevate/Services/HabitService.cs
  Backend/Elevate/Services/IFriendshipService.cs
  Backend/Elevate/Services/IHabitLogService.cs
  Backend/Elevate/Services/IHabitService.cs
  Backend/Elevate/Services/IUserService.cs
  Backend/Elevate/Services/UserService.cs
Labels: enhancement

#94 91 refactor backend code and structure
  .gitignore
  Backend/Elevate/Controllers/FriendshipController.cs
  compose.yaml
  documentation/_minted-elevate/one-dark
  documentation/_minted-elevate/one-dark.pygstyle
  documentation/elevate.tex
Labels: documentation, enhancement

#95 81 improve backend error handling on requests
  Backend/Elevate.Common/Exceptions/Exceptions.cs
  Backend/Elevate.Common/Utilities/UserPermissionUtility.cs
  Backend/Elevate.Data/Database/ElevateDbContext.cs
  Backend/Elevate.Data/Repository/HabitLogRepository.cs
  Backend/Elevate.Data/Repository/HabitRepository.cs
  Backend/Elevate/Middleware/GlobalExceptionHandler.cs
  Backend/Elevate/Services/HabitLogService.cs
  Backend/Elevate/Services/UserService.cs
Labels: enhancement

#97 81 improve backend error handling on requests
  Backend/Elevate.Common/Exceptions/Exceptions.cs
  Backend/Elevate.Data/Repository/FriendshipRepository.cs
  Backend/Elevate.Data/Repository/HabitRepository.cs
  Backend/Elevate.Data/Repository/UserRepository.cs
  Backend/Elevate/Controllers/HabitController.cs
  Backend/Elevate/Middleware/GlobalExceptionHandler.cs
  Backend/Elevate/Profiles/AutoMapperProfile.cs
  Backend/Elevate/Services/FriendshipService.cs
  Backend/Elevate/Services/HabitService.cs
  Backend/Elevate/Services/IFriendshipService.cs
  Backend/Elevate/Services/UserService.cs
Labels: enhancement

#98 Fixed wrong error message
  Backend/Elevate/Services/UserService.cs
Labels: bug, enhancement

#99 Fixed issues with updating
  Backend/Elevate.Data/Repository/HabitLogRepository.cs
  Backend/Elevate.Models/HabitLog/HabitLogUpdateDto.cs
  Backend/Elevate/Controllers/HabitLogController.cs
  Backend/Elevate/Profiles/AutoMapperProfile.cs
  Backend/Elevate/Services/HabitLogService.cs
  Backend/Elevate/Services/HabitService.cs
  Backend/Elevate/Services/IHabitLogService.cs
Labels: bug

#101 74 mobile fetch habits from backend
  Mobile-frontend/.editorconfig
  Mobile-frontend/src/app/.models/Habit.model.ts
  Mobile-frontend/src/app/app.component.html
  Mobile-frontend/src/app/app.component.ts
  Mobile-frontend/src/app/app.routes.ts
  Mobile-frontend/src/app/components/task-card/task-card.component.html
  Mobile-frontend/src/app/components/task-card/task-card.component.scss
  Mobile-frontend/src/app/components/task-card/task-card.component.ts
  Mobile-frontend/src/app/pages/create-account-page/create-account-page.page.scss
  Mobile-frontend/src/app/pages/create-account-page/create-account-page.page.ts
  Mobile-frontend/src/app/pages/create-habit/create-habit.page.html
  Mobile-frontend/src/app/pages/create-habit/create-habit.page.scss
  Mobile-frontend/src/app/pages/create-habit/create-habit.page.spec.ts
  Mobile-frontend/src/app/pages/create-habit/create-habit.page.ts
  Mobile-frontend/src/app/pages/feed/feed.page.html
  Mobile-frontend/src/app/pages/feed/feed.page.scss
  Mobile-frontend/src/app/pages/feed/feed.page.ts
  Mobile-frontend/src/app/pages/login-page/login-page.page.html
  Mobile-frontend/src/app/pages/login-page/login-page.page.ts
  Mobile-frontend/src/app/services/auth.service.ts
  Mobile-frontend/src/app/services/habit.service.spec.ts
  Mobile-frontend/src/app/services/habit.service.ts
  Mobile-frontend/src/app/services/toast.service.spec.ts
  Mobile-frontend/src/app/services/toast.service.ts
  Mobile-frontend/src/global.scss
Labels: enhancement

#104 Removed time fields from UpdateDto and habitLog delete endpoint
  Backend/Elevate.Models/Friendship/FriendshipModel.cs
  Backend/Elevate.Models/Friendship/FriendshipUpdateDto.cs
  Backend/Elevate/Controllers/HabitLogController.cs
Labels: enhancement

#109 Fixed due date when generating habit logs. Updated docker compose setup
  Backend/Elevate.Data/Repository/HabitLogGeneratorRepository.cs
  compose-backend.yaml
Labels: bug, enhancement

#114 Added feed endpoint.
  Backend/Elevate.Data/Repository/FeedRepository.cs
  Backend/Elevate/Controllers/FeedController.cs
  Backend/Elevate/Extensions/IServiceCollectionExtension.cs
  Backend/Elevate/Services/FeedService.cs
  Backend/Elevate/Services/HabitLogService.cs
  Backend/Elevate/Services/IFeedService.cs
Labels: enhancement

#115 Sync wirh backend
  .gitignore
  Backend/Elevate.Data/Repository/FeedRepository.cs
  Backend/Elevate.Data/Repository/HabitLogGeneratorRepository.cs
  Backend/Elevate.Tests/.gitignore
  Backend/Elevate.Tests/Elevate.Tests.csproj
  Backend/Elevate.Tests/UnitTests.cs
  Backend/Elevate/Controllers/FeedController.cs
  Backend/Elevate/Elevate.sln
  Backend/Elevate/Extensions/IServiceCollectionExtension.cs
  Backend/Elevate/Services/FeedService.cs
  Backend/Elevate/Services/HabitLogService.cs
  Backend/Elevate/Services/IFeedService.cs
  documentation/_minted-elevate/one-dark
  documentation/_minted-elevate/one-dark.pygstyle
  documentation/elevate.pdf
  documentation/elevate.tex
Labels: enhancement

#116 Sync with web-frontend
  .gitignore
  Backend/Elevate.Data/Repository/FeedRepository.cs
  Backend/Elevate.Data/Repository/HabitLogGeneratorRepository.cs
  Backend/Elevate.Tests/.gitignore
  Backend/Elevate.Tests/Elevate.Tests.csproj
  Backend/Elevate.Tests/UnitTests.cs
  Backend/Elevate/Controllers/FeedController.cs
  Backend/Elevate/Elevate.sln
  Backend/Elevate/Extensions/IServiceCollectionExtension.cs
  Backend/Elevate/Services/FeedService.cs
  Backend/Elevate/Services/HabitLogService.cs
  Backend/Elevate/Services/IFeedService.cs
  documentation/_minted-elevate/one-dark
  documentation/_minted-elevate/one-dark.pygstyle
  documentation/elevate.pdf
  documentation/elevate.tex
Labels: enhancement

#121 111 create feed page
  Backend/Elevate.Data/Database/ElevateDbContext.cs
  Backend/Elevate.Data/Repository/FeedRepository.cs
  Backend/Elevate.Data/Repository/UserRepository.cs
  Backend/Elevate.Models/Post/PostDto.cs
  Backend/Elevate.Models/Post/PostModel.cs
  Backend/Elevate.Models/User/UserUpdateDto.cs
  Backend/Elevate/Controllers/FeedController.cs
  Backend/Elevate/Extensions/IServiceCollectionExtension.cs
  Backend/Elevate/Profiles/AutoMapperProfile.cs
  Backend/Elevate/Services/FeedService.cs
  Backend/Elevate/Services/IFeedService.cs
  web-frontend/package-lock.json
  web-frontend/package.json
  web-frontend/src/app/app.routes.ts
  web-frontend/src/app/components/feed/task/task.component.html
  web-frontend/src/app/components/feed/task/task.component.scss
  web-frontend/src/app/components/feed/task/task.component.spec.ts
  web-frontend/src/app/components/feed/task/task.component.ts
  web-frontend/src/app/models/habitlog.model.ts
  web-frontend/src/app/models/post.model.ts
  web-frontend/src/app/models/user.model.ts
  web-frontend/src/app/pages/feed/feed.component.html
  web-frontend/src/app/pages/feed/feed.component.scss
  web-frontend/src/app/pages/feed/feed.component.spec.ts
  web-frontend/src/app/pages/feed/feed.component.ts
  web-frontend/src/app/services/feed.service.spec.ts
  web-frontend/src/app/services/feed.service.ts
Labels: bug, enhancement

#122 Updated documentation
  documentation/elevate.pdf
  documentation/elevate.tex
Labels: enhancement

#132 129 create endpoint to return pending friend requests
  Backend/Elevate.Data/Repository/FriendshipRepository.cs
  Backend/Elevate.Models/Friendship/FriendshipDto.cs
  Backend/Elevate.Models/Friendship/FriendshipUpdateDto.cs
  Backend/Elevate.Models/Friendship/ValidFriendShipStatusAttribute.cs
  Backend/Elevate.Models/Habit/ValidFrequencyTypeAttribute.cs
  Backend/Elevate/Controllers/FriendshipController.cs
  Backend/Elevate/Profiles/AutoMapperProfile.cs
  Backend/Elevate/Profiles/IntToFriendshipStatusEnumConverter.cs
  Backend/Elevate/Services/FriendshipService.cs
  Backend/Elevate/Services/IFriendshipService.cs
Labels: enhancement

#133 Added streak tracking.
  Backend/Elevate.Data/Repository/HabitLogRepository.cs
  Backend/Elevate/Extensions/IServiceCollectionExtension.cs
  Backend/Elevate/Services/HabitLogService.cs
  Backend/Elevate/Services/IStreakService.cs
  Backend/Elevate/Services/StreakBackgroundService.cs
  Backend/Elevate/Services/StreakService.cs
Labels: enhancement

#134 Updated documentation.
  documentation/elevate.pdf
  documentation/elevate.tex
Labels: documentation

#149 147 create get friendships endpoint
  Backend/Elevate.Data/Repository/FriendshipRepository.cs
  Backend/Elevate/Controllers/AuthController.cs
  Backend/Elevate/Controllers/ChallengeController.cs
  Backend/Elevate/Controllers/FeedController.cs
  Backend/Elevate/Controllers/FriendshipController.cs
  Backend/Elevate/Controllers/HabitController.cs
  Backend/Elevate/Controllers/HabitLogController.cs
  Backend/Elevate/Controllers/UserController.cs
  Backend/Elevate/Extensions/IServiceCollectionExtension.cs
  Backend/Elevate/Services/Challenge/ChallengeService.cs
  Backend/Elevate/Services/Challenge/IChallengeService.cs
  Backend/Elevate/Services/Feed/FeedService.cs
  Backend/Elevate/Services/Feed/IFeedService.cs
  Backend/Elevate/Services/Friendship/FriendshipService.cs
  Backend/Elevate/Services/Friendship/IFriendshipService.cs
  Backend/Elevate/Services/Habit/HabitService.cs
  Backend/Elevate/Services/Habit/IHabitService.cs
  Backend/Elevate/Services/HabitLog/HabitLogGenerationBackgroundService.cs
  Backend/Elevate/Services/HabitLog/HabitLogGeneratorService.cs
  Backend/Elevate/Services/HabitLog/HabitLogService.cs
  Backend/Elevate/Services/HabitLog/IHabitLogGeneratorService.cs
  Backend/Elevate/Services/HabitLog/IHabitLogService.cs
  Backend/Elevate/Services/Streak/IStreakService.cs
  Backend/Elevate/Services/Streak/StreakBackgroundService.cs
  Backend/Elevate/Services/Streak/StreakService.cs
  Backend/Elevate/Services/User/IUserService.cs
  Backend/Elevate/Services/User/UserService.cs
Labels: enhancement

#150 Updated documentation and added a new endpoint
  Backend/Elevate.Data/Repository/FriendshipRepository.cs
  Backend/Elevate/Controllers/AuthController.cs
  Backend/Elevate/Controllers/ChallengeController.cs
  Backend/Elevate/Controllers/FeedController.cs
  Backend/Elevate/Controllers/FriendshipController.cs
  Backend/Elevate/Controllers/HabitController.cs
  Backend/Elevate/Controllers/HabitLogController.cs
  Backend/Elevate/Controllers/UserController.cs
  Backend/Elevate/Extensions/IServiceCollectionExtension.cs
  Backend/Elevate/Services/Challenge/ChallengeService.cs
  Backend/Elevate/Services/Challenge/IChallengeService.cs
  Backend/Elevate/Services/Feed/FeedService.cs
  Backend/Elevate/Services/Feed/IFeedService.cs
  Backend/Elevate/Services/Friendship/FriendshipService.cs
  Backend/Elevate/Services/Friendship/IFriendshipService.cs
  Backend/Elevate/Services/Habit/HabitService.cs
  Backend/Elevate/Services/Habit/IHabitService.cs
  Backend/Elevate/Services/HabitLog/HabitLogGenerationBackgroundService.cs
  Backend/Elevate/Services/HabitLog/HabitLogGeneratorService.cs
  Backend/Elevate/Services/HabitLog/HabitLogService.cs
  Backend/Elevate/Services/HabitLog/IHabitLogGeneratorService.cs
  Backend/Elevate/Services/HabitLog/IHabitLogService.cs
  Backend/Elevate/Services/Streak/IStreakService.cs
  Backend/Elevate/Services/Streak/StreakBackgroundService.cs
  Backend/Elevate/Services/Streak/StreakService.cs
  Backend/Elevate/Services/User/IUserService.cs
  Backend/Elevate/Services/User/UserService.cs
  compose-backend.yaml
  documentation/_minted-elevate/one-dark.pygstyle
  documentation/elevate.pdf
  documentation/elevate.tex
Labels: enhancement

#154 Fixed error when sending a friend request.
  Backend/Elevate/Program.cs
  Backend/Elevate/Services/Friendship/FriendshipService.cs
Labels: bug

#155 Fixed friendship endpoint issue
  Backend/Elevate/Program.cs
  Backend/Elevate/Services/Friendship/FriendshipService.cs
Labels: bug

#156 126 add challenge button to habits
  web-frontend/.gitignore
  web-frontend/src/app/app.routes.ts
  web-frontend/src/app/pages/habits/habits.component.html
  web-frontend/src/app/pages/habits/habits.component.scss
  web-frontend/src/app/pages/habits/habits.component.spec.ts
  web-frontend/src/app/pages/habits/habits.component.ts
  web-frontend/src/app/services/habit.service.spec.ts
  web-frontend/src/app/services/habit.service.ts
Labels: enhancement
